import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {discoverConnection,resolveDirectory,loadPreferences,savePreferences,backupDirectory} from '../connection.js';
async function fixture(t){const base=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'rime-connection-')));t.after(()=>fs.rm(base,{recursive:true,force:true}));return {base,home:path.join(base,'another-user'),systemApp:path.join(base,'system/Squirrel.app'),platform:'darwin',env:{}};}
async function install(app,version='1.2.3'){const contents=path.join(app,'Contents');await fs.mkdir(path.join(contents,'MacOS'),{recursive:true});await fs.mkdir(path.join(contents,'SharedSupport'),{recursive:true});await fs.writeFile(path.join(contents,'Info.plist'),`<plist><dict><key>CFBundleIdentifier</key><string>im.rime.inputmethod.Squirrel</string><key>CFBundleVersion</key><string>${version}</string></dict></plist>`);await fs.writeFile(path.join(contents,'MacOS/Squirrel'),'fixture',{mode:0o700});for(const name of ['default.yaml','squirrel.yaml'])await fs.writeFile(path.join(contents,'SharedSupport',name),'{}\n');}
test('system install is checked first and home is obtained from the supplied current user',async t=>{const f=await fixture(t);await install(f.systemApp);await fs.mkdir(path.join(f.home,'Library/Rime'),{recursive:true});const c=await discoverConnection(f);assert.equal(c.ready,true);assert.equal(c.confirmed,false);assert.equal(c.userDir,path.join(f.home,'Library/Rime'));assert.equal(c.sharedDir,path.join(f.systemApp,'Contents/SharedSupport'));assert.equal(c.checks[0].label,'系统鼠须管');assert.equal(c.canDeploy,true);});
test('per-user installation is discovered when the system installation is absent',async t=>{const f=await fixture(t),app=path.join(f.home,'Library/Input Methods/Squirrel.app');await install(app);await fs.mkdir(path.join(f.home,'Library/Rime'),{recursive:true});const c=await discoverConnection(f);assert.equal(c.appPath,app);assert.equal(c.ready,true);assert.equal(c.checks[0].found,false);});
test('system installation wins over a per-user installation',async t=>{const f=await fixture(t);await install(f.systemApp,'1');await install(path.join(f.home,'Library/Input Methods/Squirrel.app'),'2');const c=await discoverConnection(f);assert.equal(c.version,'1');});
test('missing directories return setup information without creating the user directory',async t=>{const f=await fixture(t),c=await discoverConnection(f);assert.equal(c.ready,false);assert.equal(c.issues.length,2);await assert.rejects(fs.stat(path.join(f.home,'Library/Rime')),/ENOENT/);});
test('saved directories can connect a copy but cannot reload the native input method',async t=>{const f=await fixture(t);await install(f.systemApp);const copy=path.join(f.base,'copy');await fs.mkdir(copy);const c=await discoverConnection({...f,preferences:{userDir:copy,sharedDir:path.join(f.systemApp,'Contents/SharedSupport'),confirmed:true}});assert.equal(c.ready,true);assert.equal(c.confirmed,true);assert.equal(c.userDir,copy);assert.equal(c.canDeploy,false);assert.ok(backupDirectory(f.base,c).startsWith(path.join(f.base,'.data/backups/')));});
test('explicit launch paths override saved directories',async t=>{const f=await fixture(t);await install(f.systemApp);const one=path.join(f.base,'one'),two=path.join(f.base,'two');await fs.mkdir(one);await fs.mkdir(two);const c=await discoverConnection({...f,env:{RIME_USER_DIR:two},preferences:{userDir:one,confirmed:true}});assert.equal(c.userDir,two);assert.equal(c.source.userDir,'environment');});
test('a resources directory without default configs is not accepted',async t=>{const f=await fixture(t);await fs.mkdir(f.home,{recursive:true});const c=await discoverConnection({...f,preferences:{userDir:f.home,sharedDir:f.home}});assert.equal(c.ready,false);assert.ok(c.issues.some(x=>x.includes('default.yaml')));});
test('tilde expands against the current user and unsafe relative paths are rejected',()=>{assert.equal(resolveDirectory('~/Library/Rime','/different/home'),'/different/home/Library/Rime');assert.throws(()=>resolveDirectory('relative/path'),/绝对路径/);assert.throws(()=>resolveDirectory('/tmp/\0'),/有效/);});
test('saved settings persist separately from Rime config and preserve confirmation',async t=>{const f=await fixture(t),file=path.join(f.base,'.data/settings.json');assert.deepEqual(await loadPreferences(file),{});await savePreferences(file,{userDir:'/tmp/one',sharedDir:'/tmp/two',confirmed:true});assert.deepEqual(await loadPreferences(file),{userDir:'/tmp/one',sharedDir:'/tmp/two',confirmed:true});assert.equal((await fs.stat(file)).mode&0o777,0o600);});
test('invalid launch paths produce setup issues rather than aborting startup',async t=>{const f=await fixture(t);const c=await discoverConnection({...f,env:{RIME_USER_DIR:'relative'}});assert.equal(c.ready,false);assert.ok(c.issues.some(x=>x.includes('设置无效')));});
test('different user directories have independent backup scopes',async t=>{const f=await fixture(t);const one={userDir:'/one',nativeUserDir:'/native'},two={userDir:'/two',nativeUserDir:'/native'};assert.notEqual(backupDirectory(f.base,one),backupDirectory(f.base,two));assert.equal(backupDirectory(f.base,{userDir:'/native',nativeUserDir:'/native'}),path.join(f.base,'.data/backups'));});
