const wiki = slug => `https://github.com/rime/home/wiki/${slug}`;
const doc = (id,category,title,desc,steps,extra={})=>({id,category,title,desc,steps,kind:'官方说明',source:wiki('UserGuide'),checked:'2026-10-05',...extra});
export const articles = [
 doc('select','选字与编辑','选字、确认和翻页','候选条是可以用键盘操作的小菜单。',['数字键选对应候选，空格确认高亮项。','↑ ↓ 移动选择；Page Up / Page Down 翻页。','默认配置还有 - / =、逗号 / 句号等翻页绑定，但取决于是否已有候选、是否正在翻页。','语句流方案的空格只确认词，句末标点或回车才提交整句。'],{keys:['Space','↑','↓','Page Down'],setting:'candidates',demo:'select'}),
 doc('edit','选字与编辑','输入了一半，怎么修改？','先在尚未提交的编码里编辑，不必删掉整句话。',['← → 移动输入位置；Home / End 跳到两端。','Mac 的 Delete 删除光标前的字符，Fn + Delete 删除光标后的字符。','Esc 清空当前未完成的输入。'],{keys:['←','→','Esc'],demo:'edit'}),
 doc('raw','中英文','直接输入字母，而不是候选字','有时你只是想输入一段拼音、代码或用户名。',['普通方案中，回车通常直接提交原始输入码。','Shift + Return 或 Control + Return 可提交格式化后的编码；具体表现取决于方案。','语句流的回车用于提交句子，请先切到临时西文再确认编码。'],{keys:['Return','Shift + Return'],setting:'keyboard',demo:'raw'}),
 doc('switch','中英文','输入到一半，切到英文','切换键如何处理已经打出的编码，是可以选择的。',['临时英文：保留字母，回车提交后回到中文。','提交候选：先输出当前中文候选，再进入英文。','提交编码：先输出字母编码，再进入英文。','也可以禁用单个 Shift 切换键，避免误触。'],{setting:'keyboard',source:wiki('CustomizationGuide'),demo:'shift'}),
 doc('menu','方案与字形','找到方案菜单','换方案、繁简、全半角、标点模式都在这里。',['切到 Rime 输入法，在可输入文字的地方按 F4 或 Control + `。','菜单中选择已启用的方案，或选择当前方案提供的状态开关。','菜单快捷键可以在“按键习惯”中修改。'],{keys:['F4','Control + `'],setting:'keyboard'}),
 doc('simplified','方案与字形','繁体、简体，随时切换','大多数朙月拼音系方案通过转换过滤器输出简体。',['打开方案菜单，找到“漢字 / 汉字”一类选项。','是否支持转换由当前方案决定；每个方案的开关名称也可能不同。','“默认字形”设置影响新会话；已经记住的状态可能由 save_options 保留。'],{setting:'language',source:wiki('CustomizationGuide')}),
 doc('fullwidth','标点与符号','全角和半角到底影响什么？','中文模式里也有两套标点映射。',['方案菜单中的全角 / 半角控制符号形态。','英文标点开关是另一个维度；开启后通常直接输出西文符号。','这里的标点编辑器只修改所选方案的半角映射，不改变全角映射。'],{setting:'punctuation'}),
 doc('punctuation','标点与符号','一个键，可以输出一个或一组符号','Rime 支持直接提交、成对引号和候选符号表。',['单个映射对应一个符号；配对映射交替输出开引号、闭引号。','列表映射会出现符号候选；可选数字或重复按原键轮换。','第一版界面支持把单个键改成指定字符；恢复继承可回到方案原来的配对或列表行为。'],{setting:'punctuation',demo:'punctuation'}),
 doc('symbols','标点与符号','输入数学、希腊字母和特殊符号','部分方案导入了 symbols 预设，可以按编码找符号。',['先在“方案解剖”检查 recognizer 是否支持 / 开头的符号输入。','支持时试试 /sx（数学）、/xl（希腊字母）等编码。','这不是所有方案都自带的能力；没有响应时先检查方案配置。'],{source:wiki('CustomizationGuide'),setting:'pipeline'}),
 doc('forget','词库与记忆','把误选的词从记忆中移除','让一个不想要的词不再因为误选而排在前面。',['重新输入相同编码，让那个词出现在候选栏。','用 ↑ ↓ 把选择移到它上面。','Mac 上按 Shift + Fn + Delete。只能删除用户词库记录；原始词库中的词只取消调频。'],{keys:['Shift + Fn + Delete'],demo:'forget'}),
 doc('learn','词库与记忆','让 Rime 记住我的常用词','词库学习和词频调整属于方案行为。',['某些方案会把组合出的新词写入用户词典。','在“语言与词库”里可以调整该方案是否启用用户词库。','第一版不编辑或删除真实用户词库文件，保留你的学习记录。'],{source:wiki('CustomizationGuide'),setting:'language'}),
 doc('phrase','词库与记忆','给常用句子一个短码','自定义短语适合地址、签名和固定说法。',['需要方案接入 custom_phrase 对应的 table_translator。','文字、编码、权重通常保存在制表符分隔的短语文件。','第一版提供原理和入口，尚未接管短语表编辑；避免把普通词库与短语表混在一起。'],{source:wiki('UserGuide'),kind:'官方说明 · 待支持'}),
 doc('applications','应用习惯','让终端、浏览器各有默认语言','应用默认语言和输入法全局切换是不同层级。',['在“应用习惯”选择应用，设为默认中文或英文。','删除自定义项会恢复鼠须管自带的应用规则；不等于强制中文。','应用的行内编辑、Vim 模式等兼容选项会保留。'],{source:wiki('CustomizationGuide'),setting:'apps'}),
 doc('deploy','设置与排错','设置保存了，为什么还没变化？','Rime 在部署时合并并编译配置。',['先保存待应用修改，再点击“重新部署”。','部署期间输入法可能短暂无法输入中文。','本工具区分“配置已保存”“已请求部署”和“编译产物已更新”，不会把请求成功当成部署成功。','如果没有观察到新产物，请从系统输入法菜单手动部署并查看日志。'],{source:wiki('CustomizationGuide'),setting:'history'}),
 doc('inherit','设置与排错','恢复继承，而不是猜一个默认值','个性化设置像盖在原配置上的透明纸。',['控件修改写入 .custom.yaml 的 patch 中。','“恢复继承”删除这个设置的覆盖，其他覆盖会保留。','软件更新时原配置能继续更新，你的补丁也能保留。'],{source:wiki('CustomizationGuide'),setting:'candidates'}),
 doc('backup','设置与排错','想回到修改之前','每次应用修改前，原始文本都会保存一份。',['在“修改记录”里选择某次修改并恢复。','恢复前会检查文件是否又被修改；有变化时拒绝直接覆盖。','恢复配置后仍需要重新部署；配置备份不包含用户词库。'],{source:wiki('UserData'),setting:'history'}),
 doc('double','方案与字形','小鹤双拼是怎样工作的？','双拼通过拼写规则，把两次击键映射成一个音节。',['声母和韵母编码规则在 speller 的拼写运算中。','双拼可以复用朙月拼音词库，不必另做整套汉字词表。','“方案解剖”会显示你的词典、拼写规则和真实组件顺序。'],{source:wiki('RimeWithSchemata'),setting:'pipeline'}),
 doc('reverse','方案与字形','不会读的字，尝试笔画反查','朙月拼音系常用反引号引入笔画查询。',['先在“方案解剖”查看 reverse_lookup 的前缀和词典。','你的双拼方案使用 stroke，h / s / p / n / z 对应一、丨、丿、丶、乙。','只有声明并安装了反查词典的方案才具备此功能。'],{source:wiki('UserGuide'),setting:'pipeline'}),
 doc('recipe','配方与社区','配方：把一套输入习惯带走','plum 配方把方案安装与定制动作组合起来。',['配方可以安装方案、声明自定义配置，也可以重建一组输入习惯。','配置重建与用户词库同步是两件事；配方不自动包含你的学习历史。','老配方里的横排写法已过时：在你当前的鼠须管上应使用 candidate_list_layout。'],{source:wiki('Recipes'),kind:'官方配方',setting:'appearance'}),
 doc('horizontal','设置与排错','旧教程的“横排”为什么无效？','旧键 style/horizontal 已被新版鼠须管移除。',['使用 candidate_list_layout: linear 设置候选横排。','text_orientation 控制文字方向，和候选排列是不同的设置。','本机默认配置和鼠须管 CHANGELOG 都可以核实这项迁移。'],{source:'https://github.com/rime/squirrel/blob/1.1.2/CHANGELOG.md',kind:'源码核实',setting:'appearance'}),
 doc('chromium','设置与排错','浏览器地址栏的退格异常','输入法需要与浏览器的文本输入实现配合。',['Issue #906 记录了 Chromium 地址栏在非嵌入模式下的退格问题。','鼠须管自带了针对 Chrome / Edge 的行内兼容规则。','调整应用默认语言时应保留这些规则；这不能保证每个浏览器版本都没有问题。'],{source:'https://github.com/rime/squirrel/issues/906',kind:'Issue · 历史问题',setting:'apps'}),
 doc('predict','配方与社区','上屏以后，能不能接着联想？','社区有上屏联想词库，依赖对应的引擎插件。',['Discussion #2174 分享了用于 librime-predict 的简体、繁体和混合词库。','这类能力需要插件和方案接入，只有词库文件还不够。','本机尚未做插件可用性验证；此卡作为探索线索，不提供自动安装。'],{source:'https://github.com/orgs/rime/discussions/2174',kind:'社区经验 · 未验证'}),
 doc('mixed','配方与社区','五笔、拼音、粤拼可以一起探索','社区方案展示了不同编码与输出模式的组合。',['Discussion #2216 分享了五笔98与拼音混输，以及独立拼音、粤拼方案。','作者描述了繁简切换、Emoji 和词频记忆能力。','这些是作者的方案介绍，尚未在本机安装和验收。'],{source:'https://github.com/orgs/rime/discussions/2216',kind:'社区经验 · 未验证'}),
 doc('chord','配方与社区','同时按几个键，也是一种输入法','并击让一组同时按下的键成为一个输入单元。',['官方网志介绍“仓颉七曜并击”：左右手同时输入首尾字根。','键盘布局和指法是学习这类方案的关键，图形化提示比只看码表更直接。','这是另一种输入方式；不会自动改动你现有的小鹤双拼。'],{source:'https://rime.im/blog/cangjie-lumiary-chords/',kind:'官方网志'}),
 doc('ergonomic','配方与社区','可视化可以承担“记住指法”的工作','官方网志展示了分体键盘与粤拼并击的 Web 模拟器。',['模拟器根据键盘布局显示指法，让抽象规则落在具体按键上。','这给本工具一个方向：把规则翻译成位置、动作和可观察的效果。','后续可以进一步实现双拼键位练习；第一版练习区是有限的教学演示。'],{source:'https://rime.im/blog/combo-jyutping-sweep-layout/',kind:'官方网志'})
];
export const components = {
 ascii_composer:['中英文切换','解释 Shift / Caps Lock 等按键，并决定现有编码如何提交。'],recognizer:['识别特殊输入','辨认邮箱、网址、符号编码和反查前缀。'],key_binder:['按键绑定','按照输入状态把按键转成编辑、翻页或模式切换动作。'],speller:['拼写规则','处理字母与分隔符；拼写运算把双拼编码映射为音节。'],punctuator:['标点映射','根据半角 / 全角表处理标点按键。'],selector:['候选选择','处理数字选词与候选定位。'],navigator:['编码导航','在输入编码和已确认片段之间移动。'],express_editor:['直接编辑','控制回车、空格、删除等动作何时提交文字。'],fluency_editor:['语句流编辑','允许先确认词，再提交整句。'],ascii_segmentor:['西文分段','给西文输入标记片段。'],matcher:['模式匹配','按 recognizer 的模式给特殊编码分类。'],abc_segmentor:['字母分段','识别交给词典翻译的字母编码。'],punct_segmentor:['标点分段','把标点片段交给符号翻译器。'],fallback_segmentor:['兜底分段','接住其他组件未处理的片段。'],punct_translator:['符号翻译','把符号片段转换为候选符号。'],reverse_lookup_translator:['反查翻译','用辅助词典查询汉字或注音提示。'],script_translator:['拼音词句翻译','从音节与词库生成字词和句子候选。'],table_translator:['码表翻译','按编码检索码表中的字词。'],simplifier:['字形转换','根据开关和 OpenCC 配置进行字形转换。'],uniquifier:['去除重复','合并文本相同的候选，避免转换后的重复。']
};
